env:
  es6: true
  node: true
extends:
  - 'prettier'
  - 'plugin:prettier/recommended'
  # - "eslint:recommended"
  # - "plugin:@typescript-eslint/eslint-recommended"
  # - "plugin:@typescript-eslint/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - 'prettier'
  - '@typescript-eslint'
rules:
  prettier/prettier: error
  indent: 0
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-unused-vars: 0
  "@typescript-eslint/no-unused-vars": [
    "error", {
      "vars": "all",
      "args": "after-used",
      "ignoreRestSiblings": true,
      "argsIgnorePattern": "^_",
      "varsIgnorePattern": "^_" }
  ]
  no-console: 0
  no-undef: 0
  "@typescript-eslint/explicit-function-return-type": ["warn", {
    "allowExpressions": true
  }]
  "@typescript-eslint/no-use-before-define": "warn"
  "@typescript-eslint/indent": ['error', 'tab']
  "no-warning-comments": ["warn", {
    "terms":
      ["todo", "fixme", "xxx"], "location": "anywhere"
    }
  ]
 