stages:
  - build
  - dist
  # - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - build/

build:
  stage: build
  image: node:14
  before_script:
    - yarn install
  script:
    - yarn build

dist:mac:
  stage: dist
  tags:
    - mac
  only:
    - tags
  image: electronuserland/builder:wine
  before_script:
    - yarn clean
    - yarn install
    - yarn build
  script:
    - yarn dist:mac
  artifacts:
    paths:
      - dist/*.dmg
      - dist/*mac.zip
    expire_in: 1h

dist:linux:
  stage: dist
  only:
    - tags
  image: electronuserland/builder:wine
  before_script:
    - yarn clean
    - yarn install
    - yarn build
  script:
    - yarn dist:linux
  artifacts:
    paths:
      - dist/*.snap
      - dist/*.AnnImage
    expire_in: 1h

dist:win:
  stage: dist
  only:
    - tags
  image: electronuserland/builder:wine
  before_script:
    - yarn clean
    - yarn install
    - yarn build
  script:
    - yarn dist:win
  artifacts:
    paths:
      - dist/*.exe
    expire_in: 1h

# pages:
#   stage: deploy
#   only:
#     - tags
#   dependencies: 
#     - dist
#   script:
#     - mkdir .public
#     - cp -r * .public
#     - mv .public public
#   artifacts:
#     paths:
#       - public
