stages:
  - build
  - pack
  # - deploy

build:
  stage: build
  image: node:14
  before_script:
    - yarn install
  script:
    - yarn build

pack:mac:
  stage: pack
  tags:
    - mac
  only:
    - tags
  image: electronuserland/builder:wine
  before_script:
    - yarn clean
    - yarn install
    - yarn build
  script:
    - yarn dist:mac
  artifacts:
    paths:
      - dist/*.dmg
      - dist/*mac.zip
    expire_in: 1h

pack:linux:
  stage: pack
  only:
    - tags
  image: electronuserland/builder:wine
  before_script:
    - yarn clean
    - yarn install
    - yarn build
  script:
    - yarn dist:linux
  artifacts:
    paths:
      - dist/*.snap
      - dist/*.AnnImage
    expire_in: 1h

pack:win:
  stage: pack
  only:
    - tags
  image: electronuserland/builder:wine
  before_script:
    - yarn clean
    - yarn install
    - yarn build
  script:
    - yarn dist:win
  artifacts:
    paths:
      - dist/*.exe
    expire_in: 1h

# pages:
#   stage: deploy
#   only:
#     - tags
#   dependencies: 
#     - pack
#   script:
#     - mkdir .public
#     - cp -r * .public
#     - mv .public public
#   artifacts:
#     paths:
#       - public
