stages:
  - build
  - pack
  # - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - build/

build:
  stage: build
  tags:
    - docker
  image: node:14
  before_script:
    - yarn install
  script:
    - yarn build

pack:mac:
  stage: pack
  tags:
    - mac
  only:
    - tags
  before_script:
    - yarn install
  script:
    - yarn dist:mac
  artifacts:
    paths:
      - dist/*.dmg
      - dist/*mac.zip
      - dist/*.pkg
    expire_in: 1 week

pack:linux:
  stage: pack
  only:
    - tags
  tags:
    - linux
  image: electronuserland/builder:14
  before_script:
    - yarn install
  script:
    - yarn dist:linux
  artifacts:
    paths:
      - dist/*.AppImage
      - dist/*.tar.gz
      - dist/*.deb
      - dist/*.apk
      - dist/*.rpm
    expire_in: 1 week

pack:win:
  stage: pack
  only:
    - tags
  tags:
    - windows
  image: electronuserland/builder:wine
  before_script:
    - yarn install
  script:
    - yarn dist:win
  artifacts:
    paths:
      - dist/*.exe
    expire_in: 1 week

# pages:
#   stage: deploy
#   only:
#     - tags
#   dependencies: 
#     - dist
#   script:
#     - mkdir .public
#     - cp -r * .public
#     - mv .public public
#   artifacts:
#     paths:
#       - public
